---
- hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: Atualizar repositórios
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Atualizar pacotes instalados
    ansible.fultin.apt:
      upgrade: full