---
- name: Instalar pacotes apt úteis
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: Adicionar repositório Neovim
    ansible.builtin.apt_repository:
      repo: ppa:neovim-ppa/stable

  - name: Atualizar lista de pacotes (apt-get update)
    ansible.builtin.apt:
      update_cache: yes

  - name: Instalar pacotes
    ansible.builtin.apt:
      name:
        - build-essential
        - gnumeric
        - htop
        - nscd
        - neovim
        - openssh-client
        - openssh-server
        - python2
        - ssh
        - tmux
        - xterm
      state: latest

  - name: Instalar Google Chrome
    ansible.builtin.apt:
      deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  - name: Instalar Visual Studio Code
    ansible.builtin.apt:
      deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64